# Generated by Django 6.0.5 on 2026-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Starter', 'Starter'), ('Pro', 'Pro')], default='free', max_length=20),
        ),
    ]
